# Generated by Django 3.2.16 on 2024-02-26 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('USER', 'user'), ('STAFF_USER', 'staff_user')], default='user', max_length=200)),
                ('is_superuser', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('booking_location', models.CharField(max_length=200)),
                ('available_from', models.DateField()),
                ('available', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BookSpecificHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookno', models.CharField(max_length=200)),
                ('available_from', models.DateField()),
                ('available', models.DateField()),
                ('booked', models.DateField(blank=True, null=True)),
                ('is_booked', models.BooleanField(default=True)),
                ('bookHotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bookhotel')),
            ],
        ),
    ]
